features:
  comment_user_picture: 1
  comment_user_verification: 1
  favicon: 1
  node_user_picture: 1
logo:
  path: 'public://logo_0.png'
  url: ''
  use_default: 0
favicon:
  mimetype: image/png
  path: 'public://logo.png'
  url: /sites/default/files/logo.png
  use_default: 0
schemas:
  bootstrap: 8000
  imalegaon: 8000
table_responsive: '-1'
navbar_inverse: 1
region_wells:
  header: ''
  imalegaonmenu: ''
  content: ''
  footer: ''
cdn_theme: bootstrap
cdn_cache_ttl_versions: '604800'
cdn_cache_ttl_themes: '604800'
cdn_cache_ttl_assets: '0'
cdn_cache_ttl_library: '0'
apply: Apply
reset_http_request_cache: ''
table: ''
